### ISSUE TITLE
Camgirl search

### ISSUE THREAD

**Issue by lonesorvivor** [cssmfc/camgirl-bio#1]
Hi cssmfc,

how to find a camgirl if someone has changed her nickname and moved to a different site
please help

**Comment by cssmfc** [comment]
Hi @lonesorvivor , thank you for being active on camgirl-bio repository but we are not employees of CB nor MFC websites.
Usually most webcam performers use social networks to keep in touch with their audience and you should try to follow your favorite camgirl.
Kind regards, Dan N [CGC](https://camgirl.cloud/dev/)
